// 자동 생성 — scripts/import-recipe-images.mjs. 직접 수정 금지.
// 키: 레시피 제목(히어로) 또는 `${제목}__${단계번호}`.
export const RECIPE_IMAGES: Record<string, number> = {
  "폭신폭신 감자채 볶음": require('../assets/recipes/r0.jpg'),
  "폭신폭신 감자채 볶음__ingredients": require('../assets/recipes/r0_ing.jpg'),
  "폭신폭신 감자채 볶음__1": require('../assets/recipes/r0_s1.jpg'),
  "폭신폭신 감자채 볶음__2": require('../assets/recipes/r0_s2.jpg'),
  "폭신폭신 감자채 볶음__3": require('../assets/recipes/r0_s3.jpg'),
  "폭신폭신 감자채 볶음__4": require('../assets/recipes/r0_s4.jpg'),
  "달콤 촉촉 고구마 맛탕": require('../assets/recipes/r1.jpg'),
  "달콤 촉촉 고구마 맛탕__ingredients": require('../assets/recipes/r1_ing.jpg'),
  "달콤 촉촉 고구마 맛탕__1": require('../assets/recipes/r1_s1.jpg'),
  "달콤 촉촉 고구마 맛탕__2": require('../assets/recipes/r1_s2.jpg'),
  "달콤 촉촉 고구마 맛탕__3": require('../assets/recipes/r1_s3.jpg'),
  "달콤 촉촉 고구마 맛탕__4": require('../assets/recipes/r1_s4.jpg'),
  "아삭아삭 양배추 쌈장 볶음": require('../assets/recipes/r2.jpg'),
  "아삭아삭 양배추 쌈장 볶음__ingredients": require('../assets/recipes/r2_ing.jpg'),
  "아삭아삭 양배추 쌈장 볶음__1": require('../assets/recipes/r2_s1.jpg'),
  "아삭아삭 양배추 쌈장 볶음__2": require('../assets/recipes/r2_s2.jpg'),
  "아삭아삭 양배추 쌈장 볶음__3": require('../assets/recipes/r2_s3.jpg'),
  "아삭아삭 양배추 쌈장 볶음__4": require('../assets/recipes/r2_s4.jpg'),
  "상큼 달콤 토마토 달걀 볶음": require('../assets/recipes/r3.jpg'),
  "상큼 달콤 토마토 달걀 볶음__ingredients": require('../assets/recipes/r3_ing.jpg'),
  "상큼 달콤 토마토 달걀 볶음__1": require('../assets/recipes/r3_s1.jpg'),
  "상큼 달콤 토마토 달걀 볶음__2": require('../assets/recipes/r3_s2.jpg'),
  "상큼 달콤 토마토 달걀 볶음__3": require('../assets/recipes/r3_s3.jpg'),
  "상큼 달콤 토마토 달걀 볶음__4": require('../assets/recipes/r3_s4.jpg'),
  "든든한 감자 고구마 조림": require('../assets/recipes/r4.jpg'),
  "든든한 감자 고구마 조림__ingredients": require('../assets/recipes/r4_ing.jpg'),
  "든든한 감자 고구마 조림__1": require('../assets/recipes/r4_s1.jpg'),
  "든든한 감자 고구마 조림__2": require('../assets/recipes/r4_s2.jpg'),
  "든든한 감자 고구마 조림__3": require('../assets/recipes/r4_s3.jpg'),
  "든든한 감자 고구마 조림__4": require('../assets/recipes/r4_s4.jpg'),
};
